name: build

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read Nginx major version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./NGINX_MAJOR
        id: nginx_major
      -
        name: Read Nginx minor version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./NGINX_MINOR
        id: nginx_minor
      -
        name: Read Nginx revision version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./NGINX_REVISION
        id: nginx_revision
      -
        name: Read version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bcgdesign/nginx-webdav:latest
            bcgdesign/nginx-webdav:${{ steps.nginx_major.outputs.content }}
            bcgdesign/nginx-webdav:${{ steps.nginx_minor.outputs.content }}
            bcgdesign/nginx-webdav:${{ steps.nginx_revision.outputs.content }}
            bcgdesign/nginx-webdav:${{ steps.version.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
